network_fqhn: attic.home.arpa
network_dns_nameservers:
  - 127.0.0.1
  - ::1
soju_enabled: true
soju_hostname: irc.i.rvl.onl
soju_db_driver: postgres
soju_db_source: user=_soju dbname=soju host=/tmp sslmode=disable
dnscrypt_proxy_enabled: true
